### PR TITLE
add scrollbar for LazyVerticalGrid

### PR DESCRIPTION
**Pull request by walt-zhong**
add Unit test and delete useless information,please review,thanks so much!!!

### CODE REVIEW

**Comment by nanihadesuka** [comment]
@walt-zhong got superconfused as I thought I was looking at the old PR https://github.com/nanihadesuka/LazyColumnScrollbar/pull/25 🤣
(you could've just pushed new commits to the old PR just so you know)

The code and unit tests look good. Will run them and if all passes merge!

Thanks!

**Review by nanihadesuka — APPROVED** [review]

**Comment by nanihadesuka** [comment]
@walt-zhong some of the new unit tests are failing
Here is the gradle stdout:

```
> Task :lib:compileDebugUnitTestKotlin
w: file:///home/runner/work/LazyColumnScrollbar/LazyColumnScrollbar/lib/src/test/java/my/nanihadesuka/compose/ColumnScrollbarTest.kt:348:34 Parameter 'value' is never used
w: file:///home/runner/work/LazyColumnScrollbar/LazyColumnScrollbar/lib/src/test/java/my/nanihadesuka/compose/LazyColumnScrollbarTest.kt:408:34 Parameter 'value' is never used
w: file:///home/runner/work/LazyColumnScrollbar/LazyColumnScrollbar/lib/src/test/java/my/nanihadesuka/compose/LazyGridVerticalScrollbarTest.kt:410:34 Parameter 'value' is never used

> Task :lib:compileDebugUnitTestJavaWithJavac NO-SOURCE
> Task :lib:testDebugUnitTest

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the bottom - with reverse layout[ Items count: 1 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:114

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the bottom[ Items count: 1 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:144

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the top - with reverse layout[ Items count: 1 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:100

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the bottom - with reverse layout[ Items count: 1 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:236

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the top[ Items count: 1 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:128

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the top[ Items count: 1 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:223

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the top - with reverse layout [ Items count: 1 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:249

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the bottom[ Items count: 1 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:[212](https://github.com/nanihadesuka/LazyColumnScrollbar/actions/runs/6769344392/job/18458279420?pr=26#step:5:213)

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the bottom - with reverse layout[ Items count: 10 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:114

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the bottom[ Items count: 10 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:144

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the top - with reverse layout[ Items count: 10 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:100

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the bottom - with reverse layout[ Items count: 10 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:236

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the top[ Items count: 10 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:128

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the top[ Items count: 10 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:[223](https://github.com/nanihadesuka/LazyColumnScrollbar/actions/runs/6769344392/job/18458279420?pr=26#step:5:224)

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the top - with reverse layout [ Items count: 10 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:249

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the bottom[ Items count: 10 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:212

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the bottom - with reverse layout[ Items count: 100 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:114

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the bottom[ Items count: 100 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:144

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the top - with reverse layout[ Items count: 100 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:100

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the bottom - with reverse layout[ Items count: 100 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:[236](https://github.com/nanihadesuka/LazyColumnScrollbar/actions/runs/6769344392/job/18458279420?pr=26#step:5:237)

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the top[ Items count: 100 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:128

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the top[ Items count: 100 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:223

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the top - with reverse layout [ Items count: 100 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:[249](https://github.com/nanihadesuka/LazyColumnScrollbar/actions/runs/6769344392/job/18458279420?pr=26#step:5:250)

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the bottom[ Items count: 100 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:212

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the bottom - with reverse layout[ Items count: 1,000 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:114

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the bottom[ Items count: 1,000 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:144

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the top - with reverse layout[ Items count: 1,000 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:100

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the bottom - with reverse layout[ Items count: 1,000 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:236

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > move scrollbar to the top[ Items count: 1,000 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:128

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the top[ Items count: 1,000 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:223

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the top - with reverse layout [ Items count: 1,000 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:249

my.nanihadesuka.compose.LazyGridVerticalScrollbarTest > scroll list to the bottom[ Items count: 1,000 ] FAILED
    java.lang.AssertionError at LazyGridVerticalScrollbarTest.kt:212

322 tests completed, 32 failed
```

**Review by nanihadesuka — CHANGES_REQUESTED** [review]
Needs to fix unit tests. 
(you can keep this PR, no need to create a new one)

**Comment by walt-zhong** [comment]
> new

hahaha,I just want my commits to look cleaner and don't want to have too many commits 

> merge

**Review by nanihadesuka — APPROVED** [review]

**Pull request merged**
